# elastic-search
# nodes:
#   es-node-1
#   es-node-2
version: '2.2'
services:
  es-node-1:
    image: elasticsearch:7.12.1
    cpus: 0.3 # requires version 2.2
    environment:
      - node.name=es-node-1
      - cluster.name=${MY_ES_CLUSTER_NAME}
      - discovery.seed_hosts=es-node-2
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es-node-1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  es-node-2:
    image: elasticsearch:7.12.1
    cpus: 0.3 # requires version 2.2
    environment:
      - node.name=es-node-2
      - cluster.name=${MY_ES_CLUSTER_NAME}
      - discovery.seed_hosts=es-node-1
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es-node-2:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    depends_on:
      - es-node-1